### ISSUE TITLE
Handle microxrceddsgen dependency

### ISSUE THREAD

**Issue by pedro-fuoco** [ArduPilot/ardupilot_gz#19]
When following the README in a fresh computer microxrceddsgen was not installed like the rest of the dependencies, would it be possible to install it with vcs with the other packages? 
![Screenshot from 2023-06-18 19-40-16](https://github.com/ArduPilot/ardupilot_gz/assets/62964137/a0284cc2-1e53-4534-9d06-8855802191f1)
I'd happily implement this to learn more, I just want to know if there's a reason why it isn't there beforehand
@srmainwaring

**Comment by pedro-fuoco** [comment]
To go around it I followed the README at `ardupilot/library/AP_DDS/`

**Comment by srmainwaring** [comment]
> I just want to know if there's a reason why it isn't there beforehand

The `microxrceddsgen` package was included in the initial draft of the `rosdep` file for macOS. It was dropped because it is also included in the `AP_DDS` instructions and is a java project that does not have a `CMakeLists.txt` to build with `colcon` (so you'd have to build manually in any case).

**Comment by pedro-fuoco** [comment]
Fair point. I think it should be mentioned that users need to go ahead and follow this part in the `AP_DDS` instructions then. Otherwise there's no way to guess this without asking someone.
I could submit a PR to add this to the "Dependencies" part of the README, wdyt?

**Comment by pedro-fuoco** [comment]
@srmainwaring what do you think?

**Comment by tejalbarnwal** [comment]
> Fair point. I think it should be mentioned that users need to go ahead and follow this part in the `AP_DDS` instructions then. Otherwise there's no way to guess this without asking someone. I could submit a PR to add this to the "Prerequisites" part of the README

I second this

**Comment by srmainwaring** [comment]
Closed by #22
