### ISSUE TITLE
How could I start my drone and make it takeoff

### ISSUE THREAD

**Issue by Ultramarine1939-syujie** [ArduPilot/ardupilot_gz#25]
Hello,I've finished building the environment and the copter has shown in rviz2,but How could I make it takeoff?

**Comment by srmainwaring** [comment]
Hi @Ultramarine1939-syujie - for future support questions it is better to use the [ArduPilot Discourse](https://discuss.ardupilot.org/) forums as issues should usually focus on problems with the package or it development.

To takeoff you issue the usual commands in the GCS. In the case of MAVProxy the sequence is:

```bash
STABILIZE> mode guided
GUIDED> arm throttle
GUIDED> takeoff 10
```

Or something similar depending on your choice of mission.

**Comment by srmainwaring** [comment]
Closing as no further activity.
