### ISSUE TITLE
Rviz reports invalid frame ID

### ISSUE THREAD

**Issue by haavarpb** [ArduPilot/ardupilot_gz#30]
Hi, 

when I do `ros2 launch ardupilot_gz_bringup iris_runway.launch.py` I get spammed by rviz with this message:

```
[rviz2-8] Warning: Invalid frame ID "iris/odom" passed to canTransform argument target_frame - frame does not exist
[rviz2-8]          at line 93 in ./src/buffer_core.cpp
```

Also, RVIZ starts misconfigured:

![image](https://github.com/ArduPilot/ardupilot_gz/assets/11046472/2cdc5701-40dc-4a29-85f0-e5e5afdd8b96)

I could fix this by updating the Global Options Fixed Frame from `iris/odom` to `base_link`, and removing the Robot Model TF Prefix from `iris` to empty: 

![image](https://github.com/ArduPilot/ardupilot_gz/assets/11046472/b4a7e1c0-e266-4eed-86ec-d6dce2a88c9c)

After this change the aforementioned spamming continues, but with a different message

```
[rviz2-8] [INFO] [1694529493.830705912] [rviz]: Message Filter dropping message: frame 'iris/odom' at time 113.380 for reason 'discarding message because the queue is full'
```

Either the .rviz-config file is not set up correctly or some topics are incorrectly mapped.

**Comment by srmainwaring** [comment]
Hi @haavarpb. I can replicate the issue. It appears that recent changes to the remapping of `tf` generated by `robot_state_publisher` and `ros_gz_bridge` and the dropping of `tf_prefix` is causing this issue. Will work on a fix.
