### ISSUE TITLE
Prefer pathlib to os.path in launch files

### ISSUE THREAD

**Issue by srmainwaring** [ArduPilot/ardupilot_gz#35]
Update launch files to consistently use `pathlib` rather than `os.path`.

**Comment by SrijaneeBiswas** [comment]
I can take this up. What would be the acceptance criteria for this issue? 

I have a Ubuntu 22.04/ROS Humble setup.

**Comment by Ryanf55** [comment]
Hello - if you are still interested, a pull request is surely welcome.

Everwhere you see any call to `os.path`, replace it with `pathlib.Path` equivalent. 

As an example, see here:
https://github.com/ethz-asl/grid_map_geo/pull/56

**Comment by Ryanf55** [comment]
Yes, that sounds sufficient. I'll test the changes locally before merge too.

**Comment by pulak-gautam** [comment]
Hi, I have put up a pr (#47) with changes following your instructions. Kindly review the same.
Thank you for your time.
